name: Lint Web3 authorization Python library

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "python/**"

defaults:
  run:
    working-directory: python

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Upgrade pip and setuptools
        run: pip install --upgrade pip setuptools
      - name: Install test requirements
        run: pip install -e .[dev,fastapi]
      - name: Mypy type check
        run: mypy web3login/
      - name: Black syntax check
        run: black --check web3login/
